
version: "3.3"
services:
  node:
    build:  
      context: .
      dockerfile: Dockerfile
    working_dir: /home/baat-cheet
    environment:
      - NODE_ENV=development
    ports:
      - "8989:3000"
    volumes:
      - ./:./
    entrypoint: "npm start"
